[project]
name = "baktflow"
version = "0.1.0"
requires-python = ">=3.11"
description = "Baktflow - An Automated Bacterial Genome Analysis Pipeline"
readme = "README.md"
license = "GPL-3.0-or-later"
authors = [
    { name = "Oliver Schwengers", email = "oliver.schwengers@cb.jlug.de" },
    { name = "Julian M. Hahnfeld" },
    { name = "Ayche Serradj" },
    { name = "Linda Fenske" },
]
maintainers = [
    { name = "Oliver Schwengers", email = "oliver.schwengers@cb.jlug.de" }
]
# keywords = ["TODO"]
classifiers = [
    "Development Status :: 1 - Planning",
    "Programming Language :: Python",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
]
dependencies = [
    "nextflow~=25.10.4",
    "polars>=1.43.2",
    "pysimdjson~=7.0.2",
    "xopen~=2.1.0",
]

[dependency-groups]
dev = [
    "ruff>=0.16.3",
    "ty>=0.0.71"
]

[project.urls]
# Documentation = "https://readthedocs.org"
Repository = "github.com/ag-computational-bio/baktflow"
"Bug Tracker" = "https://github.com/ag-computational-bio/baktflow/issues"

[project.scripts]
baktflow = "baktflow.CLI:main"

[build-system]
requires = ["uv_build >= 0.12.3,<0.13"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "baktflow"
module-root = ""
source-include = ["nextflow_interface/**"]

[tool.ruff]
line-length = 120
