[metadata]
name = baktflow
version = 0.1.0
description = Baktflow An Automated Bacterial Genome Analysis Pipeline
long_description = file: README.md
long_description_content_type = text/markdown
author = Oliver Schwengers
author_email = oliver.schwengers@cb.jlug.de
license = MIT

[options.package_data]
baktflow = *.yaml
* = nextflow_interface/**/*

